/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuille (void);
GtkWidget* create_menu_espace_admin (void);
GtkWidget* create_gestion_d_etablissement_ (void);
GtkWidget* create_vous_ete_sure_modification_etablissement_ (void);
GtkWidget* create_affichage_etablissement_par_region (void);
GtkWidget* create_affichage_par_capacite_ (void);
GtkWidget* create_gestion_d_utilisateur (void);
GtkWidget* create_vous_ete_sure_modif_abbr (void);
GtkWidget* create_affichage_par_sexe_abbr (void);
GtkWidget* create_affichage_par_role_abbr (void);
GtkWidget* create_gestion_infirmier (void);
GtkWidget* create_vousetessureyb (void);
GtkWidget* create_affichage_par_moyenne_du_jour_yb (void);
GtkWidget* create_affichage_fiche_de_donneur_yb (void);
GtkWidget* create_gestionmedecin (void);
GtkWidget* create_checkska (void);
GtkWidget* create_affichagedetouslesdons (void);
GtkWidget* create_affichagepartypequantiteska2 (void);
GtkWidget* create_gestion_donneur (void);
GtkWidget* create_vous_etes_sur_fr_ (void);
GtkWidget* create_afficher_les_creneaux (void);
GtkWidget* create_afficher_par_historique (void);
GtkWidget* create_GDaffiche (void);
GtkWidget* create_GDsupprime (void);
GtkWidget* create_GDajoute (void);
GtkWidget* create_GDmodife (void);
GtkWidget* create_GDstatistique (void);
